apiVersion: v1
kind: Service
metadata:
  name: starterkit-service
spec:
  selector:
    app: squad-hub
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30000
